name: Update this repo's README

on:
  schedule:
    # Once a day at 9 AM
    - cron: 0 9 * * *

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@v1
        with:
          feed-url: https://newsletter.prikeshsavla.com/?format=rss
          readme-section: feed
